### PR TITLE
Fix broken sarif export

### PR DESCRIPTION
**Pull request by JarLob**
Plus upgrade sarif schema to 2.1.0

### CODE REVIEW

**Comment by phosphore** [comment]
About ba73cfdf44226ceb6ccb7e7fce2509f9a32fca4a, this is needed for some checks where no location is present afaik. Or is it a Sarif spec requirement to have at least `0:0` for the lin:col? `issue.location` could be undefined in some checks (e.g. CSP?)

**Comment by JarLob** [comment]
Yes, I was testing with different Sarif viewers like VS Code and VS. Implementation differs. First I thought skip `region` at all, but this combination is the best common denominator. Sarif also doesn't like `0:0`, so having `1:1` when no file is available doesn't change anything. The change affects only the exported sarif json file.

**Comment by phosphore** [comment]
Fair enough. Is `issue.location` always present tho? 
https://github.com/doyensec/electronegativity/pull/80/commits/ba73cfdf44226ceb6ccb7e7fce2509f9a32fca4a#diff-e97b0ce1d9051faf00c21306911cf6bcfd8a245e5783ec1a9b448dc6c8dd8966R116-R117

**Comment by JarLob** [comment]
Yes, it is `0:0` if no file. Can check `location` for undefined if you think it is better.
The final version btw is:
```javascript
startLine: issue.location.line === 0 ? 1 : issue.location.line, // This is odd, VS and VS Code highlight the line correctly, but min value is 1
startColumn: issue.location.column + 1, // sarif columns start from 1
charLength: issue.sample ? issue.sample.length : 0
```
I dropped the check for `N/A`. Just adjust indices and set `charLenth` to zero if `sample` is not available.

**Comment by phosphore** [comment]
Thank you very much @JarLob <3
I'll merge this and create a new v1.8.1 tag here and on NPM.

**Pull request merged**
