### PR TITLE
fix: load i18n in runner.js

### LINKED ISSUE #101: Error when run programmatically
**Describe the bug**

`i18n` is not loaded.

```
ReferenceError: __ is not defined
```

**To Reproduce**

1. Install 1.10.2
2. Run programmatically https://github.com/doyensec/electronegativity#programmatically

**Expected behavior**

Run successfully

**Platform (please complete the following information):**
 - OS: Win, Mac, Linux
 - Electronegativity version: 1.10.2

### PR DESCRIPTION
**Pull request by bhbs**
Fix #101

### CODE REVIEW

**Comment by phosphore** [comment]
Thanks for catching that @bhbs! :D

**Comment by carhartl** [comment]
Can you do a new release with this fix? I'm running into this, but can't seem to just access the GitHub repo for the package, because of the non-existent `main` reference: https://github.com/doyensec/electronegativity/blob/085f3cfcfa20e0d67ae9edc07506da56bddcd918/package.json#L5

**Comment by phosphore** [comment]
@carhartl now live on npm (v1.10.3 [@doyensec/electronegativity](https://www.npmjs.com/package/@doyensec/electronegativity))

**Comment by carhartl** [comment]
@phosphore Thank you so much ❤️

**Pull request merged**
